### ISSUE TITLE
Tagline is not centered

### ISSUE THREAD

**Issue by rootEnginear** [Csslandia/docs#1]
## Expected

Tagline in landing page (Csslandia is a free and open source CSS framework carefully crafted with attention to every detail.) is centered.

## Actual

It's not.

## Screenshot

![image](https://github.com/Csslandia/docs/assets/7108662/169c230e-0a32-47cd-bd37-ae7017f57163)

## Suggested Fix

Add `.x-centered` to tagline element

**Comment by jacobheap** [comment]
Thanks for letting me know about the issue, which one browser are you using?

**Comment by rootEnginear** [comment]
MS Edge Chromium 113 on Windows 10 (Sorry for late reply)
